### ISSUE TITLE
Incorrect gzip tail

### ISSUE THREAD

**Issue by Johnsik** [qnap-dev/QDK#1]
add_qpkg_tail() in qbuild is addind to qpkg something that recognaized by tar as trailing garbage.
So force tar to return warning "/bin/tar: Exiting with failure status due to previous errors"

So "sh ./aa.qpkg" is return
"aa 0.1 installation failed. Data file error.
Installation Abort."

This occurse only in terminal package installation.
If I comment add_qpkg_tail in qbuild the future installation is done also in terminal mode.

**Comment by edhongcy** [comment]
Hello Johnsik

1."/bin/tar: Exiting with failure status due to previous errors"
The return value is how to produce.

2."aa" 0.1 installation failed. Data file error.
aa.qpkg is this QDK build?

**Comment by fcwu** [comment]
@edhongcy 

In QDK2, we truncate tailing garbage in https://github.com/qnap-dev/qdk2/blob/master/QDK_2.2/bin/qbuild#L620.

I guess it's relating with @Johnsik problem

**Comment by Johnsik** [comment]
Hi edhongcy!
TS-419P II with QDK 2.2.13:
```
qbuild --create-env aa
cd aa
qbuild
sh ./build/aa_0.1.qpkg
```
result is:
```
Install QNAP package on TS-NAS...
8+1 records in
8+1 records out
./
./qinstall.sh
./qpkg.cfg
./package_routines
./built_info
0+1 records in
0+1 records out
0+1 records in
0+1 records out
aa 0.1 installation failed. Data file error.
Installation Abort.
```

Problem is ONLY when I install from terminal. There is no problem in web GUI.

If I comment `/bin/rm -fr \$_EXTRACT_DIR && exit $retval` in qbuild and after run
`/bin/tar xvf /share/HDA_DATA/.qpkg/.tmp/data.tar.gz`
I've got:
```
./
./.gitkeep
./aa.sh

gzip: stdin: decompression OK, trailing garbage ignored
/bin/tar: Child returned status 2
/bin/tar: Exiting with failure status due to previous errors
```

tar version is 1.22

**Comment by edhongcy** [comment]
Hi Johnsik

I hope you can reply to a few questions .It can accelerate to clarify my question .

1. How you take QDK 2.2.13?
2. You NAS QDK is upgrade or remove old QDK than install new QDK.

I guess it's NAS QDK incomplete upgrade issue.

**Comment by edhongcy** [comment]
@fcwu 
Thank you tell me "Truncate" bug in qbuild.
I will fix it in qdk.

**Comment by Johnsik** [comment]
@edhongcy 
1. From [QPKG Development Guidelines](http://wiki.qnap.com/wiki/QPKG_Development_Guidelines).
2. Remove old and install new.

Also I have installed [Optware-ng](https://github.com/Optware/Optware-ng). But qbuild include absolute path to utils (like /bin/tar) so it not must be a problem.

UPD. Ups... I'm try to disable Optware-ng and the problem is gone.

**Comment by Johnsik** [comment]
data.tar.gz in qpkg isn't fully correct. It content trailing garbage.
tar w/o Optware-ng use /bin/gzip from BusyBox that isn't show warning about trailing garbage.
tar with Optware-ng use /opt/bin/gzip that is show warning about trailing garbage.

**Comment by edhongcy** [comment]
Hello @Johnsik 

I use "cat" data.tar.gz.
`[/share/CACHEDEV1_DATA/aa/build] # cat data.tar.gz 
��Qo�0���Oq�xX'��@���
T{�&0��,P�j��~�*tR7��N���rv�����\�::�"
c�Z3&��F�a��I�bA`���`[�-���7:�.d�e�z+���c̕˿Y���X�����,���G�͉7�'�v{���<^̽�:OE��l�3W���~���Ɯr�
                                                                                                   ��ԓ�;S^i�G���ZW�ɐK��P����v<��=Zz�]ٖ{O��zqB'څO?�Tp�]��S����<]O�9��
q@�6��jq������V��s�Ҝ�V��z�n|1�&g�rB��E�Er���8��|mB���Qi�|�V�}l!a!�p����(��i*�9��Ӂ�8N�����z4�f�ٴ͙֛�'���9���@���ש������͑����aD�zTL����AAAAAAA^�O�7ǀ(                                        1085687375          aa                  0.1       QNAPQPKG  `

I think you say "trailing garbage" is QDK write information " 1085687375          aa                  0.1       QNAPQPKG" in end of file.
So that is QNAP deliberately stayed information not issue.
