### ISSUE TITLE
InstallToUbuntu.sh remove is deleting the whole of `/etc/config`

### ISSUE THREAD

**Issue by oddstr13** [qnap-dev/QDK#15]
https://github.com/qnap-dev/QDK/blob/cd478c7767c7456d3c6a4f3ab26b886455d49c66/InstallToUbuntu.sh#L30

**Comment by edhongcy** [comment]
Fix it
https://github.com/qnap-dev/QDK/commit/2f69b8965ee3a3ca2b389324842621c811439396
