### ISSUE TITLE
Missing dependency in InstallToUbuntu.sh for rsync

### ISSUE THREAD

**Issue by stefan-frank** [qnap-dev/QDK#16]
https://github.com/qnap-dev/QDK/blob/cd478c7767c7456d3c6a4f3ab26b886455d49c66/InstallToUbuntu.sh#L10

While building a QPKG with QDK in a Docker image I encountered the problem, that the contents of shared data wouldn't be copied in to the final package. There was no error output. Inspecting the qbuild script I found out, that there is a dependency to rsync.

It would be nice if you would add it to the required installed packages, installed by apt-get.

**Comment by edhongcy** [comment]
Hi @stefan-frank 

I add apt-get install rsync to InstallToUbuntu.sh.
https://github.com/qnap-dev/QDK/blob/master/InstallToUbuntu.sh#L10
