### ISSUE TITLE
How to build a QPKG on a Linux machine (not a QNAP)?

### ISSUE THREAD

**Issue by flaw19plane** [qnap-dev/QDK#2]
From the documentation it doesn't become clear to me how to cross-build a QPKG on a Linux machine (not being a QNAP device).

How can I start cross building a QPKG?

Or is there a virtual (image of a) QNAP device available?

**Comment by edhongcy** [comment]
Hi flaw19plane

We now only support ubuntu. You can use add repository install qdk2(QPKG build tool).
`sudo add-apt-repository -y ppa:chris-lea/node.js 
sudo add-apt-repository -y ppa:fcwu-tw/ppa 
sudo apt-get update 
sudo apt-get install -y build-essential unzip curl wget git qdk2 realpath moreutils fakeroot`
