### ISSUE TITLE
unable to install x41 QPKG on armv7l because of platform

### ISSUE THREAD

**Issue by OneCDOnly** [qnap-dev/QDK#21]
source: https://forum.qnap.com/viewtopic.php?p=745580#p745580

NAS: TS-431P2 (I think)
```
# getcfg "" Platform -f /etc/platform.conf
ARM_MS
```
So, this NAS model is a "rejected platform". 

Can anyone explain why? What is the reason for rejecting this platform? 

Thank you.

**Comment by edhongcy** [comment]
Hi @OneCDOnly 

This is NAS TS-431P2(arm-x41) platform information.
<img width="507" alt="Screen Shot 2020-04-20 at 5 42 46 PM" src="https://user-images.githubusercontent.com/9511797/79737766-64237100-832e-11ea-8504-c6368eba078e.png">

This is NAS TS-431(arm-x31) platform information.
<img width="511" alt="Screen Shot 2020-04-20 at 5 48 17 PM" src="https://user-images.githubusercontent.com/9511797/79738356-3985e800-832f-11ea-9547-4174db9b3d90.png">

You can reference doc x31 x41 use different toolchain, so x31 x41 are different model.
`uname -m ` can't distinguish between different models arm-x31 and arm-x41, so I add 'rejecting platform' variable.
doc:
https://edhongcy.gitbooks.io/qdk-quick-start-guide/content/qnap-platform-models-toolchain.html

**Comment by OneCDOnly** [comment]
Thanks for your response @edhongcy and I apologise for my delay in responding. I'm still trying to develop some usable rules to determine whether a NAS will require x31 or x41 packages. :confused: 

Can you please confirm or deny the following statements? 

- Is it true that a unit with an `armvl` arch and an `ARM_MS` platform is _always_ x31?
- And that a unit with an `armvl` arch and an `ARM_AL` platform is _always_ x41?
- Are you aware of _any_ QNAP models that will return `armvh` as an arch? 

Thank you. :nerd_face:

**Comment by edhongcy** [comment]
Hi @OneCDOnly 
1. Yes, ARM_MS platform only for x31.
2. ARM_AL platform is always x41, x41 model name maybe is TS-531P, TS-431P2. 
    So it need check /etc/platform.conf.
3. I don't know will return `armv7h` arch QNAP models.
    QNAP new arm machine is aarch64 arch

**Comment by OneCDOnly** [comment]
Thank you. That gives me something to work with. :grin:
