### ISSUE TITLE
Link -  https://cheng-yuan-hong.gitbook.io/qdk-quick-start-guide/ Is not working 

### ISSUE THREAD

**Issue by nodecentral** [qnap-dev/QDK#26]
Hi

I’m unable to reach - https://cheng-yuan-hong.gitbook.io/qdk-quick-start-guide/

````
Error: Server Error

The server encountered an error and could not complete your request.
````

is there a new address ?

**Comment by kataro92** [comment]
The link is working as expected.
https://cheng-yuan-hong.gitbook.io/qdk-quick-start-guide/
