### ISSUE TITLE
[ enhancement ] Icons

### ISSUE THREAD

**Issue by nephaste** [qnap-dev/QDK#4]
Hi Ed

Can it be possbile to use .png instead of .gif for icons files

each time i have to rename .png to .gif 
gif is too limited compared png

**Comment by edhongcy** [comment]
Hi nephaste

This enhancement add to QDK 2.2.15.
https://github.com/qnap-dev/QDK/commit/ed10938d6e05b2a55facc06f32dbffa0ef9e9283
