### ISSUE TITLE
QDK 2.3.0: QPKG failed to install due to missing Optware package (but it is installed)

### ISSUE THREAD

**Issue by station7** [qnap-dev/QDK#6]
I just built my QPKG with v.2.3.0 of the QDK but it won't installl ("Failed to install myqpkg. You must first install and enable JRE, OPT/busybox." The same QPKG worked fine when built with QDK 2.216. 

In qpkg.cfg I defined
`QPKG_REQUIRE="JRE, OPT/busybox"`
If I limit QPKG_REQUIRE to "JRE", the installation works just fine.

What did I do wrong? I have Entware installed which provides - amongst other - busybox via opkg.

Thanks for looking at it or helping me to adjust my requirement.

**Comment by edhongcy** [comment]
Hi station7

QNAP NAS no supported "Optware".  so QDK 2.3.0 remove any Optware check script.
 
if you need QDK examine "Entware-ng" package.
I suggest modifying the "QPKG_REQUIRE" setting.
`QPKG_REQUIRE="JRE, Entware-ng"`

I hope it helps you.

**Comment by station7** [comment]
Hi edhongcy, 

thank you so much for your reply. I get the point of Optware being no longer support, but the OPT requirements checks have been completely removed. Wouldn't it be an option to implement those OPT requirements checks, because the additional packages cane be provided from entware/entware-ng?

Would you do me a favor and explain to me, what is the easiest way to "patch in" the OPT requirements checks you disables with your commit for the support of the notification center? From how I understood your commit, only the function "check_requirements(){", the init routine "init()" have to be patched, but what about   "-append_install_msg()" and "-append_remove_msg()"?

A little help would be highly appreciated...

Many thanks and greetings from Germany!

**Comment by station7** [comment]
Thank you so much, I'll give it a try!
